### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nordzilla** [nordzilla/cargo-doc-gen#16]
**A roadmap of functionality to support before an initial release.**

---
### Misc.
- #18 Implement a CLI
- [ ] [#19] Check for config file
- [ ] [#3] Support deserializing config
  - [ ] [#20] Create config examples/help section

---
### Generate an AST
- [ ] [#7] Generate AST(s) from relevant files in a rust project.
  - [ ] [#21] Parallelize AST generation

---
### Generate a DocTree
- [ ] [#4] Create DocTree(s) from Rust AST(s)
  - [ ] [#26] Handle custom attributes
  - [ ] [#25] Determine if a function locally panics.
  - [ ] [#9] Determine if a function may transitively panic
  - [ ] [#23] Parallelize DocTree creation

---
### Generate DocComments
- [ ] [#5] Generate DocComments
  - [ ] [#22] Merge DocComments
  
---
### Insert DocComments into files
- [ ] [#17] Insert DocComments into files
  - [ ] [#24] Parallelize DocComment insertion
